import type { Project } from '@/types/projects'

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: 'Coaching Growth Platform',
    description: 'A fully custom platform converting first-time visitors into paying subscribers for FitCoach Pro.',
    client_name: 'FitCoach Pro',
    service_type: 'SaaS MVP',
    status: 'discovery',
    payment_status: 'pending',
    fixed_price: 8000,
    currency: 'USD',
    start_date: '2026-08-01',
    deadline: '2026-11-30',
    completion_pct: 12,
    is_client_visible: false,
    team: [
      { id: 'hi', name: 'Hamza Iqbal', avatar_url: null, role: 'Admin' },
      { id: 'sa', name: 'Sara Ahmed', avatar_url: null, role: 'Manager' },
      { id: 'zm', name: 'Zain Malik', avatar_url: null, role: 'Member' },
    ],
    tasks: [
      { id: 't1', title: 'Discovery call notes', status: 'done', priority: 'medium', assignee_name: 'Hamza Iqbal', assignee_avatar: null, due_date: '2026-08-05' },
      { id: 't2', title: 'Architecture proposal', status: 'in_progress', priority: 'high', assignee_name: 'Sara Ahmed', assignee_avatar: null, due_date: '2026-08-20' },
    ],
    milestones: [
      { id: 'm1', title: 'Kickoff complete', due_date: '2026-08-15', completed_at: '2026-08-12' },
      { id: 'm2', title: 'Architecture signed', due_date: '2026-09-01', completed_at: null },
    ],
    updates: [],
    files: [],
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Patient Acquisition System',
    description: 'A full-featured patient acquisition and tracking CRM for Acme Health Co, integrating with their existing EMR system.',
    client_name: 'Acme Health Co',
    service_type: 'Custom CRM',
    status: 'in_progress',
    payment_status: 'partial',
    fixed_price: 12000,
    currency: 'USD',
    start_date: '2026-07-01',
    deadline: '2026-10-31',
    completion_pct: 68,
    is_client_visible: true,
    team: [
      { id: 'hi', name: 'Hamza Iqbal', avatar_url: null, role: 'Admin' },
      { id: 'sa', name: 'Sara Ahmed', avatar_url: null, role: 'Manager' },
    ],
    tasks: [
      { id: 't1', title: 'Set up database schema', status: 'done', priority: 'high', assignee_name: 'Sara Ahmed', assignee_avatar: null, due_date: '2026-08-05' },
      { id: 't2', title: 'Build appointment booking API', status: 'in_progress', priority: 'urgent', assignee_name: 'Hamza Iqbal', assignee_avatar: null, due_date: '2026-08-11' },
      { id: 't3', title: 'Design patient dashboard UI', status: 'todo', priority: 'high', assignee_name: 'Sara Ahmed', assignee_avatar: null, due_date: '2026-08-14' },
    ],
    milestones: [
      { id: 'm1', title: 'Database & API complete', due_date: '2026-08-15', completed_at: null },
      { id: 'm2', title: 'Core UI delivered', due_date: '2026-09-01', completed_at: '2026-08-20' },
      { id: 'm3', title: 'Beta testing', due_date: '2026-10-01', completed_at: null },
    ],
    updates: [
      { id: 'u1', author_name: 'Hamza Iqbal', author_avatar: null, content: 'ssakshksa', is_client_visible: false, created_at: '2026-08-12T12:00:00Z', time_ago: 'Just now' },
      { id: 'u2', author_name: 'Hamza Iqbal', author_avatar: null, content: 'API endpoints for patient booking are 80% complete. On track for milestone delivery.', is_client_visible: true, created_at: '2026-08-10T12:00:00Z', time_ago: '2 days ago' },
    ],
    files: [
      { id: 'f1', file_name: 'project-brief.pdf', file_size: '1.2 MB', uploaded_at: 'Aug 1', is_client_visible: true, mime_type: 'application/pdf' },
      { id: 'f2', file_name: 'wireframes-v2.fig', file_size: '8.4 MB', uploaded_at: 'Aug 5', is_client_visible: false, mime_type: 'application/figma' },
      { id: 'f3', file_name: 'api-docs.md', file_size: '34 KB', uploaded_at: 'Aug 8', is_client_visible: false, mime_type: 'text/markdown' },
    ],
    created_at: '2026-07-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'B2B Pipeline OS',
    description: 'Business Relationship Platform & Pipeline OS cutting weekly outreach from 40 hours to 5.',
    client_name: 'GrowthFounders',
    service_type: 'Workflow Automation',
    status: 'review',
    payment_status: 'partial',
    fixed_price: 15000,
    currency: 'USD',
    start_date: '2026-05-01',
    deadline: '2026-08-25',
    completion_pct: 85,
    is_client_visible: true,
    team: [
      { id: 'sa', name: 'Sara Ahmed', avatar_url: null, role: 'Manager' },
      { id: 'zm', name: 'Zain Malik', avatar_url: null, role: 'Member' },
    ],
    tasks: [],
    milestones: [],
    updates: [],
    files: [],
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Tax AI MVP',
    description: 'AI tax assistant reducing filing time from 10 hours to 30 minutes.',
    client_name: 'SoloFile Ltd',
    service_type: 'SaaS MVP',
    status: 'delivered',
    payment_status: 'paid',
    fixed_price: 18000,
    currency: 'USD',
    start_date: '2026-01-01',
    deadline: '2026-07-15',
    completion_pct: 100,
    is_client_visible: true,
    team: [
      { id: 'hi', name: 'Hamza Iqbal', avatar_url: null, role: 'Admin' },
      { id: 'zm', name: 'Zain Malik', avatar_url: null, role: 'Member' },
    ],
    tasks: [],
    milestones: [],
    updates: [],
    files: [],
    created_at: '2026-01-01T00:00:00Z',
  },
]
