import type { Doc } from '@/types/docs'

export const MOCK_DOCS: Doc[] = [
  {
    id: '1',
    title: 'Client Onboarding SOP',
    content: 'Standard operating procedure for onboarding new clients...',
    category: 'SOPs',
    is_shared: true,
    author_id: 'user-hi',
    author_name: 'Hamza Iqbal',
    author_avatar: null,
    updated_at: '2026-08-12T10:00:00Z',
    time_ago: '2 hours ago',
  },
  {
    id: '2',
    title: 'Project Brief Template',
    content: null,
    category: 'Templates',
    is_shared: true,
    author_id: 'user-sa',
    author_name: 'Sara Ahmed',
    author_avatar: null,
    updated_at: '2026-08-09T00:00:00Z',
    time_ago: '3 days ago',
  },
  {
    id: '3',
    title: 'GrowthOS Discovery Notes',
    content: null,
    category: 'Meeting Notes',
    is_shared: false,
    author_id: 'user-zm',
    author_name: 'Zain Malik',
    author_avatar: null,
    updated_at: '2026-08-11T00:00:00Z',
    time_ago: 'Yesterday',
  },
  {
    id: '4',
    title: 'Tech Stack Research: AI Frameworks',
    content: null,
    category: 'Research',
    is_shared: true,
    author_id: 'user-hi',
    author_name: 'Hamza Iqbal',
    author_avatar: null,
    updated_at: '2026-08-05T00:00:00Z',
    time_ago: '1 week ago',
  },
]
