import type { Task } from '@/types/tasks'

export const MOCK_TASKS: Task[] = [
  {
    id: '1',
    title: 'Design patient dashboard UI',
    description: null,
    project_id: '2',
    project_name: 'Patient Acquisition System',
    assigned_to: 'user-sa',
    assignee_name: 'Sara Ahmed',
    assignee_avatar: null,
    status: 'todo',
    priority: 'high',
    due_date: '2026-08-14',
    subtask_total: 0,
    subtask_done: 0,
    created_at: '2026-08-10T00:00:00Z',
  },
  {
    id: '2',
    title: 'Discovery call follow-up deck',
    description: null,
    project_id: '1',
    project_name: 'Coaching Growth Platform',
    assigned_to: 'user-hi',
    assignee_name: 'Hamza Iqbal',
    assignee_avatar: null,
    status: 'todo',
    priority: 'low',
    due_date: '2026-08-11',
    subtask_total: 0,
    subtask_done: 0,
    created_at: '2026-08-09T00:00:00Z',
  },
  {
    id: '3',
    title: 'Review client feedback doc',
    description: null,
    project_id: '3',
    project_name: 'B2B Pipeline OS',
    assigned_to: 'user-sa',
    assignee_name: 'Sara Ahmed',
    assignee_avatar: null,
    status: 'todo',
    priority: 'high',
    due_date: '2026-08-11',
    subtask_total: 0,
    subtask_done: 0,
    created_at: '2026-08-09T00:00:00Z',
  },
  {
    id: '4',
    title: 'Build appointment booking API',
    description: null,
    project_id: '2',
    project_name: 'Patient Acquisition System',
    assigned_to: 'user-hi',
    assignee_name: 'Hamza Iqbal',
    assignee_avatar: null,
    status: 'in_progress',
    priority: 'urgent',
    due_date: '2026-08-11',
    subtask_total: 3,
    subtask_done: 1,
    created_at: '2026-08-08T00:00:00Z',
  },
  {
    id: '5',
    title: 'CRM integration spec',
    description: null,
    project_id: '3',
    project_name: 'B2B Pipeline OS',
    assigned_to: 'user-sa',
    assignee_name: 'Sara Ahmed',
    assignee_avatar: null,
    status: 'in_progress',
    priority: 'medium',
    due_date: '2026-08-12',
    subtask_total: 0,
    subtask_done: 0,
    created_at: '2026-08-07T00:00:00Z',
  },
  {
    id: '6',
    title: 'Set up database schema',
    description: null,
    project_id: '2',
    project_name: 'Patient Acquisition System',
    assigned_to: 'user-hi',
    assignee_name: 'Hamza Iqbal',
    assignee_avatar: null,
    status: 'done',
    priority: 'high',
    due_date: '2026-08-05',
    subtask_total: 2,
    subtask_done: 2,
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: '7',
    title: 'Write tax parsing module',
    description: null,
    project_id: '4',
    project_name: 'Tax AI MVP',
    assigned_to: 'user-zm',
    assignee_name: 'Zain Malik',
    assignee_avatar: null,
    status: 'done',
    priority: 'medium',
    due_date: '2026-07-10',
    subtask_total: 0,
    subtask_done: 0,
    created_at: '2026-07-01T00:00:00Z',
  },
]
