import type { Notification } from '@/types/notifications'

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    type: 'follow_up_due',
    title: 'Follow-up due: PayFlow SaaS',
    body: 'Marcus Webb follow-up was due today',
    time_ago: '2h ago',
    is_read: false,
    reference_type: 'lead',
    reference_id: '4',
  },
  {
    id: '2',
    type: 'ticket_raised',
    title: 'New ticket from NovaBuild',
    body: 'James Okafor raised a ticket on NovaBuild project',
    time_ago: '5h ago',
    is_read: false,
    reference_type: 'ticket',
    reference_id: '1',
  },
  {
    id: '3',
    type: 'blog_needs_review',
    title: 'Post ready for review',
    body: "Zain's post is ready for your review",
    time_ago: 'Yesterday',
    is_read: false,
    reference_type: 'blog_post',
    reference_id: '3',
  },
  {
    id: '4',
    type: 'project_updated',
    title: 'GrowthOS moved to Negotiation',
    body: 'Lead updated by Sara Ahmed',
    time_ago: 'Yesterday',
    is_read: true,
    reference_type: 'lead',
    reference_id: '2',
  },
  {
    id: '5',
    type: 'task_assigned',
    title: 'Task assigned to you',
    body: 'Discovery call follow-up deck was assigned to you',
    time_ago: '2 days ago',
    is_read: true,
    reference_type: 'task',
    reference_id: '2',
  },
  {
    id: '6',
    type: 'lead_assigned',
    title: 'New lead assigned',
    body: 'ClinicOS has been assigned to your queue',
    time_ago: '3 days ago',
    is_read: true,
    reference_type: 'lead',
    reference_id: '1',
  },
]
