import type { BlogPost } from '@/types/blog'

export const MOCK_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'How We Built a Custom CRM in 6 Weeks',
    slug: 'how-we-built-a-custom-crm-in-6-weeks',
    excerpt:
      'A behind-the-scenes look at our development process, the tech stack we chose, and what we learned.',
    body: null,
    cover_image_url: null,
    author_id: 'user-hi',
    author_name: 'Hamza Iqbal',
    author_avatar: null,
    category: 'Case Study',
    tags: ['crm', 'development', 'case-study'],
    status: 'published',
    publish_date: '2026-07-28',
    published_at: '2026-07-28T00:00:00Z',
    seo_title: null,
    seo_description: null,
    reading_time_minutes: 8,
    is_featured: true,
    allow_comments: true,
    created_at: '2026-07-20T00:00:00Z',
    updated_at: '2026-07-28T00:00:00Z',
  },
  {
    id: '2',
    title: 'AI Agents for Solopreneurs: What Actually Works',
    slug: 'ai-agents-for-solopreneurs-what-actually-works',
    excerpt:
      "We tested 14 AI agent frameworks so you don't have to. Here's what actually shipped to production.",
    body: null,
    cover_image_url: null,
    author_id: 'user-sa',
    author_name: 'Sara Ahmed',
    author_avatar: null,
    category: 'AI & Automation',
    tags: ['ai', 'agents', 'solopreneurs'],
    status: 'published',
    publish_date: '2026-08-03',
    published_at: '2026-08-03T00:00:00Z',
    seo_title: null,
    seo_description: null,
    reading_time_minutes: 12,
    is_featured: false,
    allow_comments: true,
    created_at: '2026-07-25T00:00:00Z',
    updated_at: '2026-08-03T00:00:00Z',
  },
  {
    id: '3',
    title: 'The Real Cost of Manual Lead Management',
    slug: 'the-real-cost-of-manual-lead-management',
    excerpt:
      'Tracking leads in spreadsheets costs more than you think — in time, in deals lost, and in team sanity.',
    body: null,
    cover_image_url: null,
    author_id: 'user-zm',
    author_name: 'Zain Malik',
    author_avatar: null,
    category: 'CRM & Sales',
    tags: ['leads', 'crm', 'sales'],
    status: 'in_review',
    publish_date: null,
    published_at: null,
    seo_title: null,
    seo_description: null,
    reading_time_minutes: 6,
    is_featured: false,
    allow_comments: true,
    created_at: '2026-08-08T00:00:00Z',
    updated_at: '2026-08-10T00:00:00Z',
  },
  {
    id: '4',
    title: 'Building a Patient Booking System: Case Study',
    slug: 'building-a-patient-booking-system-case-study',
    excerpt:
      'From requirements to go-live in 10 weeks — how we built a fully integrated booking system for a healthcare provider.',
    body: null,
    cover_image_url: null,
    author_id: 'user-hi',
    author_name: 'Hamza Iqbal',
    author_avatar: null,
    category: 'Case Study',
    tags: ['healthcare', 'booking', 'case-study'],
    status: 'draft',
    publish_date: null,
    published_at: null,
    seo_title: null,
    seo_description: null,
    reading_time_minutes: null,
    is_featured: false,
    allow_comments: true,
    created_at: '2026-08-10T00:00:00Z',
    updated_at: '2026-08-12T00:00:00Z',
  },
]
